# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyp/slambook2/practice/Chapter3-homework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyp/slambook2/practice/Chapter3-homework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyp/slambook2/practice/Chapter3-homework/CMakeFiles /home/zyp/slambook2/practice/Chapter3-homework//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyp/slambook2/practice/Chapter3-homework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ORB

# Build rule for target.
ORB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ORB
.PHONY : ORB

# fast build rule for target.
ORB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/build
.PHONY : ORB/fast

#=============================================================================
# Target rules for targets named hw10

# Build rule for target.
hw10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hw10
.PHONY : hw10

# fast build rule for target.
hw10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw10.dir/build.make CMakeFiles/hw10.dir/build
.PHONY : hw10/fast

src/ORBFeature.o: src/ORBFeature.cpp.o
.PHONY : src/ORBFeature.o

# target to build an object file
src/ORBFeature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBFeature.cpp.o
.PHONY : src/ORBFeature.cpp.o

src/ORBFeature.i: src/ORBFeature.cpp.i
.PHONY : src/ORBFeature.i

# target to preprocess a source file
src/ORBFeature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBFeature.cpp.i
.PHONY : src/ORBFeature.cpp.i

src/ORBFeature.s: src/ORBFeature.cpp.s
.PHONY : src/ORBFeature.s

# target to generate assembly for a file
src/ORBFeature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBFeature.cpp.s
.PHONY : src/ORBFeature.cpp.s

src/ORBextractor.o: src/ORBextractor.cc.o
.PHONY : src/ORBextractor.o

# target to build an object file
src/ORBextractor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBextractor.cc.o
.PHONY : src/ORBextractor.cc.o

src/ORBextractor.i: src/ORBextractor.cc.i
.PHONY : src/ORBextractor.i

# target to preprocess a source file
src/ORBextractor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBextractor.cc.i
.PHONY : src/ORBextractor.cc.i

src/ORBextractor.s: src/ORBextractor.cc.s
.PHONY : src/ORBextractor.s

# target to generate assembly for a file
src/ORBextractor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/ORBextractor.cc.s
.PHONY : src/ORBextractor.cc.s

src/apps/hw10.o: src/apps/hw10.cpp.o
.PHONY : src/apps/hw10.o

# target to build an object file
src/apps/hw10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw10.dir/build.make CMakeFiles/hw10.dir/src/apps/hw10.cpp.o
.PHONY : src/apps/hw10.cpp.o

src/apps/hw10.i: src/apps/hw10.cpp.i
.PHONY : src/apps/hw10.i

# target to preprocess a source file
src/apps/hw10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw10.dir/build.make CMakeFiles/hw10.dir/src/apps/hw10.cpp.i
.PHONY : src/apps/hw10.cpp.i

src/apps/hw10.s: src/apps/hw10.cpp.s
.PHONY : src/apps/hw10.s

# target to generate assembly for a file
src/apps/hw10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw10.dir/build.make CMakeFiles/hw10.dir/src/apps/hw10.cpp.s
.PHONY : src/apps/hw10.cpp.s

src/parameter.o: src/parameter.cpp.o
.PHONY : src/parameter.o

# target to build an object file
src/parameter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/parameter.cpp.o
.PHONY : src/parameter.cpp.o

src/parameter.i: src/parameter.cpp.i
.PHONY : src/parameter.i

# target to preprocess a source file
src/parameter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/parameter.cpp.i
.PHONY : src/parameter.cpp.i

src/parameter.s: src/parameter.cpp.s
.PHONY : src/parameter.s

# target to generate assembly for a file
src/parameter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORB.dir/build.make CMakeFiles/ORB.dir/src/parameter.cpp.s
.PHONY : src/parameter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ORB"
	@echo "... hw10"
	@echo "... src/ORBFeature.o"
	@echo "... src/ORBFeature.i"
	@echo "... src/ORBFeature.s"
	@echo "... src/ORBextractor.o"
	@echo "... src/ORBextractor.i"
	@echo "... src/ORBextractor.s"
	@echo "... src/apps/hw10.o"
	@echo "... src/apps/hw10.i"
	@echo "... src/apps/hw10.s"
	@echo "... src/parameter.o"
	@echo "... src/parameter.i"
	@echo "... src/parameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

